---
title: "Master's thesis"
author: "Rafael Sergio Pérez Pujol <p> Contact: RafaelSergio.Perez@alu.uclm.es"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
subtitle: "Máster Universitario en Modelización y Análisis de Datos Económicos <p> (MUMADE - UCLM)"
lang: es
---

```{r setup, include = FALSE}
# Chunk settings
knitr::opts_chunk$set(echo = FALSE, 
                      eval = TRUE, 
                      message = FALSE,
                      warning = FALSE,
                      comment = '',
                      fig.width = 10,
                      fig.height = 4)
```

```{r start, include = FALSE}
# Initial cleaning of the environment
rm(list = ls())

# Installation of non-installed packages
packages <- c("readxl",
              "tidyverse",
              "tidyr",
              "ggplot2",
              "fpp3",
              "tsibble",
              "knitr",
              "kableExtra",
              "dplyr",
              "bibliometrix",
              "plotly",
              "tidyquant",
              "bibtex",
              "rbibutils",
              "RCurl")

installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Activation of required libraries
library(readxl)
library(tidyverse)
library(tidyr)
library(ggplot2)
library(fpp3)
library(tsibble)
library(knitr)
library(kableExtra)
library(dplyr)
library(bibliometrix)
library(plotly)
library(tidyquant)
library(bibtex)
library(rbibutils)
library(RCurl)
library(bibliometrixData)
```

```{r import}
# Import .csv file
# file (scopus_data.csv) available at https://github.com/sperezpujol/mumade_tfm/blob/main/scopus_data.csv.
scopus_data <- 
  convert2df(file = "scopus_data.csv",
             dbsource = "scopus",
             format = "csv")

# First references ordered by number of citations (descending)
head(scopus_data["TC"])
```

```{r descriptive 1}
# 1.1. Descriptive analysis (tables)
results <- 
  biblioAnalysis(scopus_data)

summary(results,
        k = 10,
        pause = F,
        width = 130)
```

```{r descriptive 2}
# 1.2. Descriptive analysis (plots)
plot(x = results,
     k = 20,
     pause = F)
```

```{r descriptive 3}
# 1.3. Most cited references
most_cited <- 
  citations(scopus_data,
            field = "article",
            sep = ";")

cbind(most_cited$Cited[1:20])
```

```{r biblioshiny}
# 1.4. Activation of analysis in the biblioshiny() web interface.
#biblioshiny()
```

```{r analysis 1, fig.height = 10}
# 2. Co-citation analysis: intellectual structure of the "sustainable entrepreneurship" field

# 2.1. references co-citation analysis
NetMatrix_1 <- 
  biblioNetwork(scopus_data,
                analysis = "co-citation",
                network = "references",
                sep = ";")
net_1 =
  networkPlot(NetMatrix_1, 
              n = 50, 
              Title = "Red de co-citas de publicaciones",
              type = "fruchterman",
              size.cex = TRUE,
              size = 20,
              remove.multiple = FALSE,
              labelsize = 1,
              edgesize = 10,
              edges.min = 5)
```

```{r analysis 2, fig.height = 10}
# 2.2. journal/source co-citation analysis
scopus_data_2 = 
  metaTagExtraction(scopus_data,
                    "CR_SO",
                    sep=";")

NetMatrix_2 <- 
  biblioNetwork(scopus_data_2,
                analysis = "co-citation", 
                network = "sources", 
                sep = ";")

net_2 = networkPlot(NetMatrix_2, 
                n = 50, 
                Title = "Red de co-citas de revistas", 
                type = "auto", 
                size.cex = TRUE, 
                size = 15, 
                remove.multiple = FALSE, 
                labelsize = 1,
                edgesize = 10, 
                edges.min = 5)
```

```{r analysis 3, fig.height = 10}
# 3. Conceptual structure - Co-Word Analysis

# 3.1. Co-word Analysis through Keyword co-occurrences
NetMatrix_3 <- 
  biblioNetwork(scopus_data,
                analysis = "co-occurrences", 
                network = "keywords", 
                sep = ";")
net_3 = networkPlot(NetMatrix_3,
                  normalize = "association",
                  n = 50, 
                  Title = "Co-ocurrencias de palabras clave",
                  type = "fruchterman",
                  size.cex = TRUE,
                  size = 20,
                  remove.multiple = F,
                  edgesize = 10,
                  labelsize = 5,
                  label.cex = TRUE,
                  label.n = 30,
                  edges.min = 2)
```

```{r analysis 4, fig.height = 10}
# Country collaboration network
scopus_data_3 <- 
  metaTagExtraction(scopus_data, 
                    Field = "AU_CO", 
                    sep = ";")
NetMatrix_6 <- 
  biblioNetwork(scopus_data_3, 
                analysis = "collaboration",  
                network = "countries", 
                sep = ";")
net_6 = networkPlot(NetMatrix_6,  
                  n = dim(NetMatrix_6)[1], 
                  Title = "Red de colaboración entre países",
                  type = "circle", 
                  size = 10,
                  size.cex = T,
                  edgesize = 1,
                  labelsize = 0.6, 
                  cluster = "none")
```

